# environment.yaml
name: mash_utils_files_p312b
dependencies:
  - python>=3.12.0
  - pip
  - pip:
    - ipykernel
    - pytest
    - pytest_check
    - radon
    - ruff
    - coverage
    - hatch
    #Package deps
    - pathlib
    - pandas
    - polars
    - pydantic>=2
    - pyarrow
    - pydantic-settings
    - boltons
    - paramiko
    # - gnupg
    - minio
    - boto3
    - universal_pathlib
    - smart_open[s3]
    - paramiko
    - python-gnupg 
    - xsdata[lxml]
    - ibis-framework[polars,pandas]
    #This package
    - -e .
    #Other Mountain Ash Packages
    - -e ../mountainash-constants
    - -e ../mountainash-settings
    - -e ../mountainash-auth-settings
    - -e ../mountainash-data
    - -e ../mountainash-utils-os
    - -e ../mountainash-utils-dataclasses
    - -e ../mountainash-utils-ssh


