# environment.yaml
name: mash_utils_files_p312
dependencies:
  - python>=3.12.0
  - pip
  - pip:
    - pathlib
    - pandas
    - polars
    - pydantic>=2
    - pyarrow
    - pydantic-settings
    - boltons
    - pytest
    - pytest_check
    - radon
    - functools
    - paramiko
    - gnupg
    - gzip
    - minio
    - boto3
    - urllib
    - universal_pathlib
    - smart_open[s3]
    - paramiko
    - python-gnupg
