[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mountainash_utils_files"
dynamic = ["version"]
description = 'Mountain Ash - Utils - Files'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Nathaniel Ramm", email = "nathaniel.ramm@discretedatascience.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "pathlib",
  "pandas",
  "polars",
  "pydantic>=2",
  "pyarrow",
  "pydantic-settings",
  "boltons",
  "paramiko",
  "gnupg",
  "minio",
  "boto3",
  "universal_pathlib",
  "smart_open[s3]",
  "paramiko",
  "python-gnupg",
  "xsdata[lxml]",
]

[project.urls]
Documentation = "https://github.com/mountainash-io/mountainash-utils-files#readme"
Issues = "https://github.com/mountainash-io/mountainash-utils-files/issues"
Source = "https://github.com/mountainash-io/mountainash-utils-files"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "src/mountainash_utils_files/__version__.py"

[tool.hatch.envs.default]
installer = "uv"

dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pytest_check",
  "mountainash_constants @ {root:uri}/../mountainash-constants",
  "mountainash_settings @ {root:uri}/../mountainash-settings",
  "mountainash_auth_settings @ {root:uri}/../mountainash-auth-settings",
  "mountainash_utils_os @ {root:uri}/../mountainash-utils-os",
  "mountainash_utils_dataclasses @ {root:uri}/../mountainash-utils-dataclasses",
  "mountainash_data @ {root:uri}/../mountainash-data",
  "mountainash_utils_ssh @ {root:uri}/../mountainash-utils-ssh",

]


# Pytest and Test Coverage - Github
[[tool.hatch.envs.test_github.matrix]]
python = ["3.11", "3.12",  "3.10" ] # "3.8", "3.9","3.9",

[tool.hatch.envs.test_github]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pytest_check",
  "mountainash_constants @ {root:uri}/temp/mountainash-constants",
  "mountainash_settings @ {root:uri}/temp/mountainash-settings",
  "mountainash_data @ {root:uri}/temp/mountainash-data",
  "mountainash_auth_settings @ {root:uri}/temp/mountainash-auth-settings",
  "mountainash_utils_os @ {root:uri}/temp/mountainash-utils-os",
  "mountainash_utils_dataclasses @ {root:uri}/temp/mountainash-utils-dataclasses",
  "mountainash_utils_ssh @ {root:uri}/temp/mountainash-utils-ssh",

]
[tool.hatch.envs.test_github.scripts]
test = "pytest"
test-cov = "coverage run -m pytest"
test-xml = "coverage xml"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
  "test-xml",
]
cov-html = [
  "coverage html",
]



# Pytest and Test Coverage - Local
[[tool.hatch.envs.test.matrix]]
python = ["3.12"]#, "3.11",  "3.10" ] # "3.8", "3.9","3.9",

[tool.hatch.envs.test]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pytest_check",
  "mountainash_constants @ {root:uri}/../mountainash-constants",
  "mountainash_settings @ {root:uri}/../mountainash-settings",
  "mountainash_auth_settings @ {root:uri}/../mountainash-auth-settings",
  "mountainash_utils_os @ {root:uri}/../mountainash-utils-os",
  "mountainash_utils_dataclasses @ {root:uri}/../mountainash-utils-dataclasses",
  "mountainash_data @ {root:uri}/../mountainash-data",
  "mountainash_utils_ssh @ {root:uri}/../mountainash-utils-ssh",

]
[tool.hatch.envs.test.scripts]
test = "pytest"
test-cov = "coverage run -m pytest"
test-xml = "coverage xml"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
  "test-xml",
]
cov-html = [
  "coverage html",
]


# Ruff Linting Checks
[tool.hatch.envs.ruff]
dependencies = [
  "ruff"
]
[tool.hatch.envs.ruff.scripts]
check = "ruff check ./src"

# Radon Complexity Checks
[tool.hatch.envs.radon]
dependencies = [
  "radon",
]
[tool.hatch.envs.radon.scripts]
radon-cc = "radon cc . -nd"
radon-mi = "radon mi . -nd"

# Mypy Type checks
[tool.hatch.envs.types]
dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/mountainash_utils_files tests}"

# Downstream package testing
# [tool.hatch.envs.test_downstream]
# dependencies = [  
#   "pytest",
#   "pytest_check",
#   "mountainash_constants @ {root:uri}/../mountainash-constants",
#   "mountainash_settings @ {root:uri}/../mountainash-settings",
#   "mountainash_auth_settings @ {root:uri}/../mountainash-auth-settings",
#   "mountainash_utils @ {root:uri}/../mountainash-utils",
#   "mountainash_utils_dataclasses @ {root:uri}/../mountainash-utils-dataclasses",
#   "mountainash_utils_dataframes @ {root:uri}/../mountainash-utils-dataframes"
#   ]


# [tool.hatch.envs.test_downstream.scripts]
# test = [#"pytest {args:tests}", 
#         "pytest ../mountainash-auth-utils-files"
# ]

# # Downstream ACRDS package testing
# [tool.hatch.envs.test_downstream_acrds]
# dependencies = [  
#   "pytest",
#   "pytest_check",
#   "mountainash_constants @ {root:uri}/../mountainash-constants",
#   "mountainash_acrds_utils_files @ {root:uri}/../mountainash-acrds-utils-files",
#   "mountainash_acrds_constants @ {root:uri}/../mountainash-acrds-constants",
#   "mountainash_utils_dataclasses @ {root:uri}/../mountainash-utils-dataclasses",
#   "mountainash_utils @ {root:uri}/../mountainash-utils"
#   ]

# [tool.hatch.envs.test_downstream_acrds.scripts]
# test = ["pytest ../mountainash-acrds-utils-files"]


# Coverage Parameters
[tool.coverage.run]
source_pkgs = ["mountainash_utils_files", "tests"]
branch = true
parallel = true
omit = [
  "src/mountainash_utils_files/__version__.py",
]

[tool.coverage.paths]
mountainash_utils_files = ["src/mountainash_utils_files", "*/mountainash-utils-files/src/mountainash_utils_files"]
tests = ["tests", "*/mountainash-utils-files/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__:",
  "if TYPE_CHECKING:",
]

[tool.hatch.build.targets.wheel]
packages = ["src/mountainash_utils_files"]