[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mountainash_utils_files"
dynamic = ["version"]
description = 'Mountain Ash - Utils - Files'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Nathaniel Ramm", email = "nathaniel.ramm@discretedatascience.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "pathlib",
  "pandas",
  "polars",
  "pydantic>=2",
  "pyarrow",
  "pydantic-settings",
  "boltons",
  "paramiko",
  "gnupg",
  "minio",
  "boto3",
  "universal_pathlib",
  "smart_open[s3]",
  "paramiko",
  "python-gnupg",
  "xsdata[lxml]",
]

[project.urls]
Documentation = "https://github.com/mountainash-io/mountainash-utils-files#readme"
Issues = "https://github.com/mountainash-io/mountainash-utils-files/issues"
Source = "https://github.com/mountainash-io/mountainash-utils-files"
