# .github/config/dependencies.yml

# Private Package Dependencies
dependencies:
  # - name: mountainash-constants
  #   org-name: mountainash-io
  - name: mountainash-data
    org-name: mountainash-io
  - name: mountainash
    org-name: mountainash-io
  - name: mountainash-settings
    org-name: mountainash-io
  # - name: mountainash-utils-dataclasses
  #   org-name: mountainash-io
  # - name: mountainash-utils-factoryclasses
  #   org-name: mountainash-io
  # - name: mountainash-utils-files
  #   org-name: mountainash-io
  # - name: mountainash-utils-gpg
  #   org-name: mountainash-io
  # - name: mountainash-utils-hamilton
  #   org-name: mountainash-io
  # - name: mountainash-utils-os
  #   org-name: mountainash-io
  # - name: mountainash-utils-rules
  #   org-name: mountainash-io
  - name: mountainash-utils-ssh
    org-name: mountainash-io
