name: Python Package using Conda

on: 
  push:
    paths:
      - 'mountainash_acrds/**'    
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest]
        python-version: ["3.11"] # "3.9", "3.10", "3.11", "3.12"
      max-parallel: 5 
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python Versions
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}        
    
    - name: Install Current package in editable mode
      run: pip install -e .     

    # - name: Install dependencies
    #   run: |
    #     conda env update --file environment_github.yml

    # - name: Lint with flake8
    #   run: |
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82,F811,F401,F403,F541,F841,E712,E713,E275 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore F405,W293,E231,E301,E302,E303,E501,E291,E222,W291,E741,E201,E741,F401,E241,E221,E265,E202,E272,E271,E123

    - name: Complexity checks with radon
      run: |
        conda install radon
        #fail on any complexity or maintainability index of D or below
        radon cc . -nd
        radon mi . -nd

    - name: Test with pytest
      run: |
        conda install pytest
        pytest
