name: Radon Complexity Checks

on: 
  push:
    paths:
      - 'src/mountainash_utils_files/**'    
  workflow_dispatch:

jobs:

  complexity-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Hatch
        run: pip install hatch

      - name: Create virtual environment
        run: hatch env create radon

      - name: Complexity checks with radon - cc
        run: hatch run radon:radon-cc

      - name: Complexity checks with radon - mi
        run: hatch run radon:radon-mi

