# name: Coverage

# on: 
#   push:
#     paths:
#       - 'src/mountainash_utils_files/**'    
#   workflow_dispatch:

# jobs:

#   coverage-checks:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python 3.12
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"
          

#       - name: Checkout private repositories - mountainash-constants
#         uses: actions/checkout@v4
#         with:          
#           repository: mountainash-io/mountainash-constants
#           ref: main
#           token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
#           path: temp/mountainash-constants
#           fetch-depth: 1     
            
#       - name: Checkout private repositories - mountainash-settings
#         uses: actions/checkout@v4
#         with:          
#           repository: mountainash-io/mountainash-settings
#           ref: main
#           token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
#           path: temp/mountainash-settings
#           fetch-depth: 1     
            
#       - name: Checkout private repositories - mountainash-auth-settings
#         uses: actions/checkout@v4
#         with:          
#           repository: mountainash-io/mountainash-auth-settings
#           ref: main
#           token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
#           path: temp/mountainash-auth-settings
#           fetch-depth: 1     
    
#       - name: Checkout private repositories - mountainash-utils
#         uses: actions/checkout@v4
#         with:          
#           repository: mountainash-io/mountainash-utils
#           ref: main
#           token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
#           path: temp/mountainash-utils
#           fetch-depth: 1     

#       - name: Checkout private repositories - mountainash-utils-dataclasses
#         uses: actions/checkout@v4
#         with:          
#           repository: mountainash-io/mountainash-utils-dataclasses
#           ref: main
#           token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
#           path: temp/mountainash-utils-dataclasses
#           fetch-depth: 1     

#       - name: Checkout private repositories - mountainash-data
#         uses: actions/checkout@v4
#         with:
#           repository: mountainash-io/mountainash-data
#           ref: main
#           token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
#           path: temp/mountainash-data   
#           fetch-depth: 1

#       - name: Checkout private repositories - mountainash-utils-ssh
#         uses: actions/checkout@v4
#         with:
#           repository: mountainash-io/mountainash-utils-ssh
#           ref: main
#           token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
#           path: temp/mountainash-utils-ssh   
#           fetch-depth: 1
  


#       - name: Install Hatch
#         run: pip install hatch

#       - name: Create virtual environment
#         run: hatch env create test_github

#       - name: Run Coverage Tests
#         run: hatch run test_github:cov

#       - name: Upload coverage reports to Codecov
#         uses: codecov/codecov-action@v4.0.1
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}
#           slug: mountainash-io/mountainash-utils-files
      