name: Pytest Runner

on: 
  pull_request_target:
    paths:
      - 'src/mountainash_utils_files/**'          
    
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.12"] #, "3.8", "3.9", "3.10","3.11",]

    steps:
      # Current Branch
      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #Set the ORGNAME
      - name: Set ORGNAME - mountainash-io
        env:
          ORGNAME: mountainash-io
        run: echo "ORGNAME=$ORGNAME" >> $GITHUB_ENV


      ###### MtAsh DEPENDENCIES ######

      # mountainash-auth-settings
      - name: Set Repo - mountainash-auth-settings
        env:
          REPO: mountainash-auth-settings
        run: echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Determine Branch to Use - ${{ env.REPO }}
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          TARGET_BRANCH_NAME: ${{ env.BRANCH_NAME }} # or set your branch name here
          DEFAULT_BRANCH_NAME: main # or set your branch name here
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$ORGNAME/$REPO/branches/$TARGET_BRANCH_NAME")
          echo "BRANCH_TO_USE=$( [ $BRANCH_EXISTS -eq 200 ] && echo $TARGET_BRANCH_NAME || echo $DEFAULT_BRANCH_NAME )" >> $GITHUB_ENV        

      - name: Checkout matching branch - ${{ env.REPO }}
        uses: actions/checkout@v4
        with:
          repository: mountainash-io/${{ env.REPO }}
          ref: ${{ env.BRANCH_TO_USE }}
          token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          path: temp/${{ env.REPO }}
          fetch-depth: 1

      # mountainash-constants
      - name: Set Repo - mountainash-constants
        env:
          REPO: mountainash-constants
        run: echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Determine Branch to Use - ${{ env.REPO }}
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          TARGET_BRANCH_NAME: ${{ env.BRANCH_NAME }} # or set your branch name here
          DEFAULT_BRANCH_NAME: main # or set your branch name here
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$ORGNAME/$REPO/branches/$TARGET_BRANCH_NAME")
          echo "BRANCH_TO_USE=$( [ $BRANCH_EXISTS -eq 200 ] && echo $TARGET_BRANCH_NAME || echo $DEFAULT_BRANCH_NAME )" >> $GITHUB_ENV        

      - name: Checkout matching branch - ${{ env.REPO }}
        uses: actions/checkout@v4
        with:
          repository: mountainash-io/${{ env.REPO }}
          ref: ${{ env.BRANCH_TO_USE }}
          token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          path: temp/${{ env.REPO }}
          fetch-depth: 1


      # mountainash-data
      - name: Set Repo - mountainash-data
        env:
          REPO: mountainash-data
        run: echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Determine Branch to Use - ${{ env.REPO }}
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          TARGET_BRANCH_NAME: ${{ env.BRANCH_NAME }} # or set your branch name here
          DEFAULT_BRANCH_NAME: main # or set your branch name here
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$ORGNAME/$REPO/branches/$TARGET_BRANCH_NAME")
          echo "BRANCH_TO_USE=$( [ $BRANCH_EXISTS -eq 200 ] && echo $TARGET_BRANCH_NAME || echo $DEFAULT_BRANCH_NAME )" >> $GITHUB_ENV        

      - name: Checkout matching branch - ${{ env.REPO }}
        uses: actions/checkout@v4
        with:
          repository: mountainash-io/${{ env.REPO }}
          ref: ${{ env.BRANCH_TO_USE }}
          token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          path: temp/${{ env.REPO }}
          fetch-depth: 1





      # mountainash-settings
      - name: Set Repo - mountainash-settings
        env:
          REPO: mountainash-settings
        run: echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Determine Branch to Use - ${{ env.REPO }}
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          TARGET_BRANCH_NAME: ${{ env.BRANCH_NAME }} # or set your branch name here
          DEFAULT_BRANCH_NAME: main # or set your branch name here
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$ORGNAME/$REPO/branches/$TARGET_BRANCH_NAME")
          echo "BRANCH_TO_USE=$( [ $BRANCH_EXISTS -eq 200 ] && echo $TARGET_BRANCH_NAME || echo $DEFAULT_BRANCH_NAME )" >> $GITHUB_ENV        

      - name: Checkout matching branch - ${{ env.REPO }}
        uses: actions/checkout@v4
        with:
          repository: mountainash-io/${{ env.REPO }}
          ref: ${{ env.BRANCH_TO_USE }}
          token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          path: temp/${{ env.REPO }}
          fetch-depth: 1


      ###### MtAsh UTILS DEPENDENCIES ######

      # mountainash-utils-dataclasses
      - name: Set Repo - mountainash-utils-dataclasses
        env:
          REPO: mountainash-utils-dataclasses
        run: echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Determine Branch to Use - ${{ env.REPO }}
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          TARGET_BRANCH_NAME: ${{ env.BRANCH_NAME }} # or set your branch name here
          DEFAULT_BRANCH_NAME: main # or set your branch name here
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$ORGNAME/$REPO/branches/$TARGET_BRANCH_NAME")
          echo "BRANCH_TO_USE=$( [ $BRANCH_EXISTS -eq 200 ] && echo $TARGET_BRANCH_NAME || echo $DEFAULT_BRANCH_NAME )" >> $GITHUB_ENV        

      - name: Checkout matching branch - ${{ env.REPO }}
        uses: actions/checkout@v4
        with:
          repository: mountainash-io/${{ env.REPO }}
          ref: ${{ env.BRANCH_TO_USE }}
          token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          path: temp/${{ env.REPO }}
          fetch-depth: 1




      # mountainash-utils-os
      - name: Set Repo - mountainash-utils-os
        env:
          REPO: mountainash-utils-os
        run: echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Determine Branch to Use - ${{ env.REPO }}
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          TARGET_BRANCH_NAME: ${{ env.BRANCH_NAME }} # or set your branch name here
          DEFAULT_BRANCH_NAME: main # or set your branch name here
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$ORGNAME/$REPO/branches/$TARGET_BRANCH_NAME")
          echo "BRANCH_TO_USE=$( [ $BRANCH_EXISTS -eq 200 ] && echo $TARGET_BRANCH_NAME || echo $DEFAULT_BRANCH_NAME )" >> $GITHUB_ENV        

      - name: Checkout matching branch - ${{ env.REPO }}
        uses: actions/checkout@v4
        with:
          repository: mountainash-io/${{ env.REPO }}
          ref: ${{ env.BRANCH_TO_USE }}
          token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          path: temp/${{ env.REPO }}
          fetch-depth: 1



      # mountainash-utils-ssh
      - name: Set Repo - mountainash-utils-ssh
        env:
          REPO: mountainash-utils-ssh
        run: echo "REPO=$REPO" >> $GITHUB_ENV

      - name: Determine Branch to Use - ${{ env.REPO }}
        env:
          TOKEN: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          TARGET_BRANCH_NAME: ${{ env.BRANCH_NAME }} # or set your branch name here
          DEFAULT_BRANCH_NAME: main # or set your branch name here
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$ORGNAME/$REPO/branches/$TARGET_BRANCH_NAME")
          echo "BRANCH_TO_USE=$( [ $BRANCH_EXISTS -eq 200 ] && echo $TARGET_BRANCH_NAME || echo $DEFAULT_BRANCH_NAME )" >> $GITHUB_ENV        

      - name: Checkout matching branch - ${{ env.REPO }}
        uses: actions/checkout@v4
        with:
          repository: mountainash-io/${{ env.REPO }}
          ref: ${{ env.BRANCH_TO_USE }}
          token: ${{ secrets.CLONE_PRIVATE_REPOS_TOKEN }}
          path: temp/${{ env.REPO }}
          fetch-depth: 1

  

      # Install Hatch
      - name: Install Hatch
        run: pip install hatch

      - name: Create virtual environment
        run: hatch env create test_github

      #Run Pytest
      - name: Run tests
        run: hatch run test_github:test

      # Run Coverage
      - name: Run Coverage Tests
        run: hatch run test_github:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mountainash-io/mountainash-utils-files

      # Sonarcloud analysis          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}             